# The URL the site will be built for
base_url = "https://shanecelis.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme = "hermit_zola"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
home_subtitle = "Approximating success one failure at a time"

# footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/papers", name = "Papers" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "mastodon", link = "https://mastodon.gamedev.place/@shanecelis" },
    { name = "github", link = "https://github.com/shanecelis" },
    { name = "twitter", link = "https://twitter.com/shanecelis" },
    { name = "email", link = "mailto:shane.celis@gmail.com" }
]
toc=true

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.disqus]
enable = false
# Take this from your Disqus account
shortname = "my-supa-dupa-blog"

[extra.author]
name = "Shane Celis"
email = "shane (dot) celis (at) gmail (dot) com"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
